Repository membraneframework/membrane_mp4_plugin, pull requests merged in 2022-01, with the labels that each got.

#33 CMAF - muxing audio and video
  .credo.exs
  README.md
  examples/muxer_cmaf.exs
  lib/membrane_mp4/movie_fragment_box.ex
  lib/membrane_mp4/muxer/cmaf.ex
  lib/membrane_mp4/muxer/cmaf/header.ex
  lib/membrane_mp4/muxer/cmaf/segment.ex
  lib/membrane_mp4/muxer/cmaf/segment_helper.ex
  lib/membrane_mp4/payloader/aac.ex
  lib/membrane_mp4/segment_index_box.ex
  mix.exs
  mix.lock
  test/fixtures/cmaf/muxed_audio_video/header.mp4
  test/fixtures/cmaf/muxed_audio_video/index.m3u8
  test/fixtures/cmaf/muxed_audio_video/playlist.m3u8
  test/fixtures/cmaf/muxed_audio_video/segment_1.m4s
  test/fixtures/cmaf/muxed_audio_video/segment_2.m4s
  test/fixtures/cmaf/out_audio_segment1.m4s
  test/fixtures/cmaf/out_audio_segment2.m4s
  test/fixtures/cmaf/out_audio_segment3.m4s
  test/fixtures/cmaf/out_audio_segment4.m4s
  test/fixtures/cmaf/out_audio_segment5.m4s
  test/fixtures/cmaf/out_video_segment2.m4s
  test/membrane_mp4/muxer/cmaf/integration_test.exs
  test/membrane_mp4/muxer/isom/integration_test.exs
  test/test_helper.exs
Labels: enhancement

#37 Release 0.12.0
  README.md
  lib/membrane_mp4/muxer/isom.ex
  mix.exs
Labels: release

#35 Making sure that ordering of pps and sps doesn't affect paremter-set change detection
  lib/membrane_mp4/payloader/h264.ex
Labels: bug
